cloud-gov/pipeline-tasks

- README.md
- bosh-errand.yml
- decrypt.yml
- diff-templates.yml
- display.yml
- encrypt.yml
- inflate.yml
- inspect.yml
- spiff-merge.yml
- write_file.yml
@dlapiduz Updated inputs in the tasks based on this is a new repo, and update the README for basic usage example
> Update tasks based on new repo

- bosh-errand.sh
- upload-release.sh
> rearrange --ca-cert option for newer bosh cli

- terraform-apply.sh
- terraform-apply.yml
- terraform-destroy.sh
- terraform-destroy.yml
@cnelson @sushiandbeer Want to give these a quick once over?
> Add terraform apply and destroy tasks

- terraform-apply.sh
- terraform-apply.yml
- terraform-destroy.sh
- terraform-destroy.yml
> Terraform updates

- terraform-apply.sh
- terraform-destroy.sh
so that it's possible to use an Instance Profile for access
> Make AWS creds params optional

- README.md
- terraform-state-to-yaml.rb
- terraform-state-to-yaml.sh
- terraform-state-to-yaml.yml
Also started added some basic documentation in the README on how to use these tasks properly.
Fixes 18F/cg-atlas#53
> Add task to take terraform state and convert output to yaml

- upload-release.sh
See https://cloudfoundry.slack.com/archives/bosh/p1458233389000292; h/t
@sushiandbeer.
> Set COLUMNS to avoid progressbar error.

- register-service-broker.sh
For example: "redis28-multinode", "mongodb30-multinode:free".
> Read pairs of service names and plans from environment.

- terraform-apply.sh
So that we can add tasks to cg-provision to show the output of `terraform plan`.
@LinuxBozo
> Configure terraform action.

- register-service-broker.sh
So I can know what I did wrong when it breaks!
> Show non-sensitive output on broker register.

- .codeclimate.yml
Experimenting with shellcheck.
> Lint shell scripts with shellcheck.

- register-service-broker.sh
> Handle unset organization.

- terraform-state-to-yaml.rb
- terraform-state-to-yaml.sh
- terraform-state-to-yaml.yml
* Fix path to script
* Add input for state file
* Fetch values from config (borrowed from upstream)
> Fix typo in task config.

- update-runtime-config.sh
- update-runtime-config.yml
> Add update-runtime-config task.

- finalize-bosh-release.sh
> Fixes issues with creating tarball in new go bosh client

- finalize-bosh-release.sh
> Fix release tarball path.

- bosh-errand.sh
- upload-release.sh
> Log in with client credentials if passed.

- bosh-errand.sh
> Fix typo on errand script.

- bosh-errand.sh
https://github.com/18F/cg-deploy-logsearch/pull/54#discussion_r103558661
> Accept arbitrary flags to run-errand.

- register-service-broker.sh
> Handle updated route format in latest cf cli.

- lint-manifest.sh
- lint-manifest.yml
Adds bosh linter task available to all pipelines
cc @jmcarp
> Add bosh linter

- ensure-service.sh
- ensure-service.yml
> Add ensure service task.

- register-service-broker.sh
For brokers that aren't run as cf apps, like elasticache: https://github.com/18F/cg-deploy-elasticache-broker/pull/1/files#diff-4e39b6ee47adc972ea04e30a02d2b1e2R115
> Optionally pass broker url to broker register task.

- terraform-apply.sh
- terraform-apply.yml
- terraform-destroy.sh
- terraform-destroy.yml
TBD: How to handle `prevent_destroy`? Is the answer...`sed`?
> [WIP] Update terraform destroy.

- terraform-apply.sh
Restore conditional notifications after logic was changed in
https://github.com/cloudfoundry-community/slack-notification-resource/pull/47.
> Ensure text file exists for detection by slack notification resource.

- terraform-apply.sh
Part of a workaround for terraform stacks that consume resources from a
separate account.
> Detect credentials from terraform variables.

- finalize-bosh-release.sh
> More shellcheck and fix quoting bits

- register-service-broker-sandboxes.yml
- register-service-broker.sh
Need to test on staging but have done some testing locally.
> Script to apply plans to sandbox accounts

- security-considerations/security-considerations.sh
- allow one empty line between the header and the body
- also add some explanations
None.
> allow one empty line between the header and the body

- sync-bucket-pipeline.yml
- sync-bucket.sh
- sync-bucket.yml
- add script, task, pipeline to sync an S3 bucket on a schedule
None
> Sync bucket

- sync-bucket-pipeline.yml
- sync-bucket.yml
> fix syntax

- sync-bucket.sh
- more variable name corrections
nonesies
> more variable name corrections

- security-considerations/generate-pipeline.py
- put pipeline file next to repo file
None
> put pipeline file next to repo file

- ensure-misbehaved-service.sh
- ensure-misbehaved-service.yml
- Add `ensure-misbehaved-service` task just to work around the aws-broker https://github.com/cloud-gov/aws-broker/issues/59
None.
> Add ensure-misbehaved-service task

- security-considerations/generate-pipeline.py
- Add a [context](https://github.com/jtarchie/github-pullrequest-resource/blame/master/README.md#L180) to PR checks so it's clear what check we're talking about
None
> add context to security considerations checks

- security-considerations/repos.txt
- add log-spammer to security considerations checks
None
> add log-spammer to security considerations check

- terraform-apply.sh
- Terraform 0.11.7 has an action to do `0.12checklist` so added that
None, just using exist terraform methods so its consistent
> Added checklist action to be used

- security-considerations/repos.txt
- Add `cloud-gov/uaa-bot`
none
> Add cloud-gov/uaa-bot

- terraform12-state-to-yaml.rb
- terraform12-state-to-yaml.sh
- terraform12-state-to-yaml.yml
- More scripts! So we can get state.yml but with terraform 12's output
Nada
> Added new scripts for terraform 12

- security-considerations/repos.txt
Adds the cloud-gov/deploy-credhub repo
We want security checks to run for the new repo
> add deploy-credhub repo

- terraform-apply.sh
- Changed how we output Terraform Plan so we can check if there is any changes. Terraform show does not work correctly because of how we modulate terraform files and modules.
- Removed old TF12 update scripts.
None
> No longer user terraform show

- terraform-apply.sh
> Van cant read and match cases

- security-considerations/repos.txt
> add some missing repos

- register-service-broker.sh
- allow orgs with test in their name, for no particular reason
-
-
None
> allow orgs with test in their name

- README.md
-
-
-
Fix bad url per https://tanzu.vmware.com/security/cve-2018-1227
> Fix concourse URL

- sync-bucket-pipeline.yml
- Update pipeline to verify commits using PGP keys
Improves security by verifying identity of commit authors when pulling code into Concourse
> update pipeline to verify commits

- bosh-errand.yml
- decrypt.yml
- diff-templates.yml
- display.yml
- encrypt.yml
- ensure-misbehaved-service.yml
- ensure-service.yml
- finalize-bosh-release.yml
- inflate.yml
- inspect.yml
- lint-manifest.yml
- register-service-broker-sandboxes.yml
- register-service-broker.yml
- security-considerations/security-considerations.yml
- sync-bucket.yml
- terraform-apply.yml
- terraform-destroy.yml
- terraform-state-to-yaml.yml
- terraform12-state-to-yaml.yml
- upload-release.yml
- write_file.yml
- This updates the scripts used by our concourse pipelines to use hardened containers
Hardened containers provide better security
> Update scripts to use hardened containers

- bosh-errand.yml
- decrypt.yml
- diff-templates.yml
- display.yml
- encrypt.yml
- ensure-misbehaved-service.yml
- ensure-service.yml
- finalize-bosh-release.yml
- inflate.yml
- inspect.yml
- register-service-broker-sandboxes.yml
- register-service-broker.yml
- security-considerations/security-considerations.yml
- sync-bucket.yml
- terraform-apply.yml
- terraform-destroy.yml
- terraform-state-to-yaml.yml
- terraform12-state-to-yaml.yml
- upload-release.yml
- write_file.yml
- Update pipeline to use general-task container
None, this pipeline was already using hardened containers. This just changes the image to our general task image.
> Use hardened containers

- terraform-apply.sh
- Without this, grep hides all the output we want to see
None
> Add missing -v to invert grep match

- register-service-broker-and-set-plan-visibility.sh
- fix typo in script name
None
> fix typo in script name

- set-plan-visibility.sh
- drop pre-emptive disable-service-access call. The upstream made a fix for this, so we shouldn't need it anymore
- fix one more reference to `blacklist`
-
None
> drop pre-emptive disable-service-access call

- terraform-apply.sh
- Fixes https://gsa-tts.slack.com/archives/GS7RNLM1N/p1713386718651949
None
> Propagate errors through grep with -o pipefail

- uaa-smoke-tests.py
- This will work with new and old URLs for SAML
None
> Updating smoke tests to reflect new url
