- inflate.sh
@dlapiduz for some reason, have to specify the `outputs` as a dir when extracting the tar before concourse will see the files in the next task
> Extract tar to output dir in inflate task

- finalize-bosh-release.sh
- finalize-bosh-release.yml
@sharms @jezhumble 
This is a reusable task that we can use to do releases. 
Has 4 inputs:
- the pipeline tasks repo
- the repo of the bosh release itself
- a tarball of the `.final_builds` dir (which in a pipeline can come from S3)
- a tarball of the `releases` dir, where new release manifests are created (again, can come from S3)
Produces 3 outputs in a `finalized-release` dir:
- a tarball of the `.final_builds` dir (which in a pipeline can be pushed back to S3)
- a tarball of the `releases` dir, where new release yml are created (again, can go to S3)
- the final release tarball (again, can go to S3)
Example pipeline: https://github.com/18F/logsearch-for-cloudfoundry/commit/fa3d4f8ec988910ff2f5180c2a540114d967149a
> Finalize a bosh release task

- terraform-apply.sh
- terraform-destroy.sh
This allows us to use modules defined elsewhere (like for example, other repos) in terraform templates. 
See: 
- https://www.terraform.io/docs/modules/usage.html
- https://www.terraform.io/docs/commands/get.html
> Add a terraform get in case there are modules being used

- upload-release.sh
- upload-release.yml
There was an existing `upload-release.sh` in this repo, but it had no corresponding task configuration.
This PR, simplifies the `upload-release.sh` script, and adds the `upload-release.yml`
This is in support of 18F/cg-atlas#57
> Add a single release upload task

- upload-release.sh
Because master-bosh doesn't have one.
> Make bosh cert optional.

- register-service-broker.sh
- register-service-broker.yml
This has been copied and pasted enough that it's probably time to extract into its own script. Note--we could also use https://github.com/cloudfoundry-community/broker-registrar-boshrelease, but I think that's sort of overkill (and unnecessary indirection) for something as simple as this. What do you think @LinuxBozo?
> Add script to register service brokers.

- bosh-errand.sh
- finalize-bosh-release.sh
Context: we're now installing the new bosh cli as `bosh-cli` in https://github.com/18F/cg-deploy-concourse-docker-image/pull/12.
> Update tasks to use bosh cli v2.

- finalize-bosh-release.sh
Because some bosh releases use semver. The current script doesn't know how to sort or bump semvers, so let bosh name new versions and sort the results with `-V`.
> Let bosh pick the release name.

- register-service-broker.sh
- register-service-broker.yml
This is needed for the work on `cg-deploy-uaa-guard-broker` to enable `--space-scoped` when registering a new service broker.
18F/cg-deploy-uaa-guard-broker#1
cc: @linuxbozo @rememberlenny
> Add CF_FLAGS for register-service-broker

- bosh-errand.sh
So that bosh-cli doesn't get mad when `BOSH_FLAGS` is empty.
> Handle empty bosh errand flags.

- terraform-apply.sh
Note: remote config is deprecated as of terraform v0.9.
Will remove the call to `remote config` once we have transitioned fully to TF 0.9
> Handle backend config for terraform v0.8 and v0.9.

- terraform-apply.sh
- terraform-apply.yml
- terraform-state-to-yaml.yml
Goes with https://github.com/18F/cg-deploy-concourse-docker-image/pull/25.
> Update for terraform 0.9.x.

- decrypt.yml
So that consumers don't have to redeclare `inputs`.
> Make inputs for decrypt task generic.

- terraform-apply.sh
Sidesteps an issue with the slack notification resource where piping terraform plans to `envsubst` crashes. Easier to simplify this logic than to debug the slack resource.
> Simplify sentinel message for terraform plan.

- terraform-apply.sh
As of terraform 0.11, `terraform apply` is interactive by default. To
use from concourse, set the `-auto-approve` flag.
Goes with https://github.com/18F/cg-deploy-concourse-docker-image/pull/39.
> Set auto-approve on terraform apply.

- finalize-bosh-release.sh
Relates to https://github.com/18F/cg-deploy-bosh/pull/270 so we can use upstream release as-is
> Update how we get the release name (and some shellcheck fixes)

- finalize-bosh-release.sh
Avoids conflicts with upstream releases whose metadata doesn't exist in
our blobstores.
> Overwrite existing release metadata.

- register-service-broker.sh
Turned out the access wasn't quite set right.  This limits sandbox plans to _only_ be able to see the sandbox s3 plans.  So we don't have to worry about this anymore on interrupt.   If you do merge, merge this PR first before this one: https://github.com/18F/cg-deploy-s3-broker/pull/24 .
> Blacklist sandbox orgs basic plans

- register-service-broker.yml
- terraform-apply.yml
This behavior has been deprecated since 4.1.0 and will eventually cause an error in later Concourse versions.
https://concourse-ci.org/download.html#v410
Keeping this [wip] for now as these task files are used throughout Concourse pipelines.
> Add necessary params

- terraform-apply.sh
Either concourse or terraform started handling empty variables
differently, so defaults are being ignored in favor of empty strings
This unsets any empty variables that start with TF_VAR_
> Unset empty TF_VAR_* variables

- finalize-bosh-release.sh
by removing the `.final_builds/` folder, it's removing all references to
vendored packages, new packages, etc. those references are needed and
nothing we do will affect upstream packages as we are using a custom
blobstore to store our custom-built releases.
[the build](https://ci.fr.cloud.gov/teams/main/pipelines/bosh-releases/jobs/build-logsearch-for-cloudfoundry-release/builds/52) was broken, but this fixes it.
Signed-off-by: Mike Lloyd <mike.lloyd@gsa.gov>
> reverting 6ded59b.

- security-considerations/security-considerations.yml
Change to registry-image type and user our docker registry mirror
None
> use registry-image with docker hub mirror

- security-considerations/security-considerations.yml
registry_mirrror is the correct property. Sorry for the typo.
None
> use the correct property

- security-considerations/repos.txt
As the cloud-gov/docker-registry-mirror repo to the list of repos w/ security checks
This ensures security checks are run on the new repo.
> add docker-registry-mirror to the list of site for security checks

- security-considerations/repos.txt
- Adds the https://github.com/cloud-gov/cg-uaa-extras-redis-migrator/ repo to this check
- Ensures that a new repo is being checked for security considerations within its PRs to maintain compliance
> Add cg-uaa-extras-redis-migrator repo

- terraform-apply.sh
- terraform-destroy.sh
terraform 0.14 supports this, and terraform >= 0.15 requires this. the behavior is notably different - with chdir, tf actually changes directories to the one specified; this means other relative paths have to be updated to reflect that
- use chdir instead of positional dir argument
None
> use chdir instead of positional dir argument

- terraform-apply.sh
- Set `+x` around commands handling credentials
This patches a security issue.
> Avoid printing credentials to logs

- uaa-smoke-tests.yml
- Replace python image with our general-task image
Uses a hardened image instead of the generally available python image
> use general-task

- bosh-logs-errand.sh
- bosh-logs-errand.yml
- Common is a s3 bucket which we will not be needing in the future. This is a copy of a bosh errand script with the common input removed
-
-
Less reliance on S3 and more usage of credhub
> removing the need for common in this script

- terraform-apply.sh
* Send `terraform get` output to a log file instead of stdout since it does not need reviewed
* Filter `terraform plan` output for lines related to state updates. Full plan output, including state updates, still exists on disk in case it needs to be reviewed
* Leave `terraform apply` output untouched for now; just test out the changes in `plan`, which is what we read more anyway
None; reducing existing output to stdout.
> Make it easier to grok Terraform output in Concourse

- terraform-apply.sh
- Like with `terraform plan`, hide non-error lines related to state updates
- Tested in `terraform plan` over the last few months. We observed no loss of useful information.
- Discussed and approved here: https://gsa-tts.slack.com/archives/GS7RNLM1N/p1710941940840279
None.
> Make terraform apply output more concise, like plan output

- terraform-apply.sh
- We don't need to double terraform apply anymore due to a bug that was fixed 5+ years ago.
None, this makes us more efficient!
> Remove Double apply

- gh-release-notifier.sh
- gh-release-notifier.yml
- Adds a task to open an issue in a github repo when a new dependent github release is availble. For example, this task will open an issue in https://github.com/cloud-gov/wazuh-agent repo when a new release is published in https://githhub.com/wazuh/wazuh.
This should help us keep bosh releases updated.
> create issues based on new github releases

- setup-commit-signing.sh
- Adds a script for concourse tasks which will need to sign git commits
- The script documents usage at the top. 
Git commit signing will enable approved and authenticated bots to automatically open PRs, simplifying our work with respect to platform updates.
> script to prepare for git commit signing
